### ISSUE TITLE
Add cursor values 'grab' and 'grabbing'

### ISSUE THREAD

**Issue by SebastianZ** [LeaVerou/css3test#103]
The cursor values `grab` and `grabbing` are currently missing. They should be added.

Sebastian

**Comment by LeaVerou** [comment]
Are they in a spec? If so, PR?

**Comment by SebastianZ** [comment]
> Are they in a spec?

They are [defined in the CSS3 UI module](https://drafts.csswg.org/css-ui-3/#cursor).

> If so, PR?

[Here](https://github.com/LeaVerou/css3test/pull/115) it is. :-)

Sebastian

**Comment by dstorey** [comment]
This in fixed now.
