### ISSUE TITLE
Rename 'text-combine-horizontal' to 'text-combine-upright'

### ISSUE THREAD

**Issue by SebastianZ** [LeaVerou/css3test#105]
In the Writing Modes spec `text-combine-horizontal` was renamed to `text-combine-upright`.
The test should be changed accordingly.

Sebastian

**Comment by LeaVerou** [comment]
Sure, pull request? :)

**Comment by SebastianZ** [comment]
Created PR #116 for it.

Sebastian

**Comment by LeaVerou** [comment]
Merged, closing. Thanks!
