### ISSUE TITLE
Get Let's Encrypt

### ISSUE THREAD

**Issue by J0WI** [LeaVerou/css3test#114]
I'll just fill one issue, but all your projects are affected :)

**Comment by LeaVerou** [comment]
Sure, if you can find a way to have it on custom domains on Github Pages.

**Comment by ChallahuAkbar** [comment]
It's super easy now: https://blog.github.com/2018-05-01-github-pages-custom-domains-https/

**Comment by J0WI** [comment]
@LeaVerou would be great if you could reconsider this.
