### ISSUE TITLE
Support display is biased

### ISSUE THREAD

**Issue by SebastianZ** [LeaVerou/css3test#117]
Due to `success === 1` and `success === 0` being treated specially, the output of `passclass()` is distorted.

You can see that at the test for 'calc()' on Firefox 43.0:
![Distorted support display](https://cloud.githubusercontent.com/assets/958943/12017839/f2a9e754-ad5b-11e5-8d33-eb57f914475b.png)
Only one of seven tests failed, though the assigned class is `slightly-buggy`, while it should actually be `almost-pass`.

Sebastian

**Comment by dstorey** [comment]
This is merged now

**Comment by SebastianZ** [comment]
Right. Thanks for closing the issue!

Sebastian
