### ISSUE TITLE
Licence File

### ISSUE THREAD

**Issue by mensing** [LeaVerou/css3test#171]
This is a really nice CSS3 test and it has some great features. The only issue that I have is that there is no licence file (that I can find) in the repository. This probably isn't a huge problem most of the time but I am working on a project that is very strict about making sure that everything used in the project has proper licences and that includes a licence file that can be pointed to. If you could add the MIT licence file to the repository with your name and the year in the right places at the top (http://opensource.org/licenses/MIT) that would be very helpful. Thanks!

**Comment by Zefling** [comment]
@LeaVerou that's right, the project does not have license file.
