### ISSUE TITLE
Error in DNS settings

### ISSUE THREAD

**Issue by SteveVaneeckhout** [LeaVerou/css3test#177]
I sometimes get [certificate](https://www.ssllabs.com/ssltest/analyze.html?d=css3test.com)/redirect errors when connecting to the website. I checked the DNS settings and noticed 1 IP address is not correct. These are the current A records:

    css3test.com.	1799	IN	A	192.30.252.154
    css3test.com.	1799	IN	A	185.199.109.153
    css3test.com.	1799	IN	A	185.199.110.153
    css3test.com.	1799	IN	A	185.199.111.153

The first IP address is causing the issues and according to [Github's help page](https://help.github.com/en/articles/setting-up-an-apex-domain#configuring-a-records-with-your-dns-provider) `192.30.252.154` should be replaced with `185.199.108.153`

**Comment by LeaVerou** [comment]
Done, thank you so much! Give it some time for the new DNS to propagate and if it still happens tomorrow or later, please let me know!
