### ISSUE TITLE
Option to only test stable features

### ISSUE THREAD

**Issue by SebastianZ** [LeaVerou/css3test#178]
There should be a way to restrict the tests to only cover stable features.

By stable, I mean all specifications listed in the latest [CSS snapshot](https://drafts.csswg.org/css-2018/) released by the CSS Working Group. When using the snapshot specifications as a reference, the option could even cover multiple of those specifications to allow the user to see the progress a browser made through the years.

Another definition of stable might be the release of a feature in two different browser engines, though that's probably harder to maintain.

Sebastian

**Comment by Zefling** [comment]
It would be necessary to add a state on each feature to be tested. It's complicated without a big change in the database (tests.js).

**Comment by SebastianZ** [comment]
That depends on whether we base this on the different features or on the spec.

If it's decided to base this on individual features, #179 would help to lay the groundwork.

Sebastian

**Comment by LeaVerou** [comment]
> By stable, I mean all specifications listed in the latest CSS snapshot released by the CSS Working Group. When using the snapshot specifications as a reference, the option could even cover multiple of those specifications to allow the user to see the progress a browser made through the years.

> Another definition of stable might be the release of a feature in two different browser engines, though that's probably harder to maintain.

I'd suggest the union of the two.

**Comment by SebastianZ** [comment]
> > By stable, I mean all specifications listed in the latest CSS snapshot released by the CSS Working Group. When using the snapshot specifications as a reference, the option could even cover multiple of those specifications to allow the user to see the progress a browser made through the years.
> 
> > Another definition of stable might be the release of a feature in two different browser engines, though that's probably harder to maintain.
> 
> I'd suggest the union of the two.

Technically speaking, does that mean that the status info should be added to the individual features (depending on their implementation status) *and* the specifications (based on the CSS snapshot)?

If so, how do you imagine the UI to look like? Would it still be one option to filter by stability or would it be split into two options for the spec. and the feature stability? I.e. what should be done if feature and spec. stability differ?

Sebastian

**Comment by SebastianZ** [comment]
The PR is merged, closing this.

Sebastian
