### ISSUE TITLE
Gecko is false negative on @counter-style

### ISSUE THREAD

**Issue by SebastianZ** [LeaVerou/css3test#185]
Firefox *does* [support the @counter-style rule](https://developer.mozilla.org/en-US/docs/Web/CSS/@counter-style#Browser_compatibility), but the test for it outputs that it doesn't.

Reason for this is that the test creates an empty rule, i.e. `@counter-style foo{}`, which is ignored. Firefox requires at least one of the descriptors to be defined.

At the time I added a test for this rule in #149 I also [filed a bug against Gecko to recognize empty @counter-style rules](https://bugzilla.mozilla.org/show_bug.cgi?id=1299097).

Though such empty at-rules actually don't make much sense and the tests should also check the descriptors at some point or rules that don't have a body like `@import`, so I suggest to change the check logic to take a complete at-rule instead of just the first part.

Sebastian

**Comment by LeaVerou** [comment]
Agreed, as long as it's optional.

**Comment by SebastianZ** [comment]
With #194 merged this is fixed now.

Sebastian
