### ISSUE TITLE
Browserscope Results

### ISSUE THREAD

**Issue by rasamassen** [LeaVerou/css3test#19]
Browserscope's API is admittedly limited (you can finally deleted defunct tests, but you cannot add new tests, reset changed tests, or group tests into categories). As a result, its records for the CSS3Test are not reflecting the actual results (says Chrome18 gets a 63 when my Chrome18 consistently gets a 56).

Based on those limits, one of two things needs to happen:
1) Simple solution is to reset or build a new user test on browserscope that will take in all the new / different data in the CSS3Test as it currently stands. Some form of versioning for the CSS3Test would aid the reality that this test will continually have to be rebuilt from time to time.
2) The more complex solution would be to use some of the backend built for the HTML5Test (with permission, of course), which is built in such a way that it could be relatively easily borrowed, and build a custom results page for the CSS3Test. This would require database access.

**Comment by rasamassen** [comment]
The browserscope site seems dead. No changes to the code in over a year.

**Comment by SebastianZ** [comment]
As @rasamassen pointed out, Browser Scope isn't working anymore, so I filed #217 to remove the related code. In #218 we can discuss new ways to save the results. Therefore, I close this issue now.

Sebastian
