### ISSUE TITLE
Sort module name by alphabetical order

### ISSUE THREAD

**Issue by Zefling** [LeaVerou/css3test#196]
There are a lot of CSS modules and it becomes complicated to navigate. By alphabetical order would be better better.

**Comment by LeaVerou** [comment]
Fine by me!

**Comment by TrisTOON** [comment]
Do you mean sorted by key (`css-sizing-3`) or by title ("Intrinsic & Extrinsic Sizing Level 3")?

Sorting modules by key seems to be more convenient for maintainers and contributors while sorting by title is maybe more practical for users.

In the first case, i saw that the names of the keys are currently a bit inconsistent.
For example, currently the key `css3-background` does not match the link to the spec (`css-backgrounds-3` / `css-backgrounds`).
So i think keys should be normalized before that (`css3-background` -> `css-backgrounds-3` for example).

Can i try to submit a PR?

**Comment by LeaVerou** [comment]
By title is more convenient for end users though, as the shortname is not immediately visible, so it will appear like a nonsensical sorting. Also, most shortnames start with `css-`.

**Comment by TrisTOON** [comment]
Should the display order reflect the order in the code?

If not, sorting specs by title could be done at runtime with `Array#sort` without having to move them in the code.

**Comment by Zefling** [comment]
I think this issue is complete.

**Comment by LeaVerou** [comment]
Great, thank you all!
