### ISSUE TITLE
Allow to check DOM features

### ISSUE THREAD

**Issue by SebastianZ** [LeaVerou/css3test#211]
Different CSS specifications add DOM related features. For example, CSS Font Loading 3 defines some interfaces and events related to loading fonts.
While they are JavaScript APIs, they are defined by the CSS specifications and are related to CSS. Therefore, they should be covered by the tests, too.

This requires a different approach for testing them, as the APIs differ depending on the specification. Houdini specs require to check whether the worklets do what they should do, the aforementioned font loading events require some font to be loaded.
This issue is meant to provide a general way to execute such tests.

Sebastian

**Comment by LeaVerou** [comment]
All we need to check is if the interfaces exist. Remember the CSS tests only check parsing; the same logic can extend to those tests. This is not WPT, nor is it meant to be.
