### ISSUE TITLE
Validity of :nth-*(-n-1)

### ISSUE THREAD

**Issue by rasamassen** [LeaVerou/css3test#22]
According to the spec, there's nothing syntactically wrong with this selector, true.

But the spec also says: The value a can be negative, but only the positive values of an+b, for n≥0, may represent an element in the document tree.

The example that follows is: html|tr:nth-child(-n+6)  /\* represents the 6 first rows of XHTML tables */

Thus, though the syntax is correct, the selector results in no positive values. Browsers (like Chrome, which currently fails this test) don't need to support input that has no representation in the document tree. I feel this selector test (it happens 4 times in the CSS3Test) should be removed as invalid.

**Comment by SebastianZ** [comment]
The tests for `:nth-*(-n-1)` selectors got removed now, so closing this issue.

Happy New Year everyone!

Sebastian
