### ISSUE TITLE
"Cheater" warning about `background-repeat` is misleading

### ISSUE THREAD

**Issue by smfr** [LeaVerou/css3test#230]
`index.html` contains text that says "WebKit claims to support CSS3 background-repeat, but it’s LYING".

WebKit certainly supports `background-repeat` (just try an example where it affects rendering). The test harness is simply triggering a bug in WebKit where it's not round-tripping through inline style, which I am fixing via https://github.com/WebKit/WebKit/pull/3292.

**Comment by LeaVerou** [comment]
I merged the PR, so closing this :)
