### ISSUE TITLE
css-shapes-1 uses incorrect 3-value position syntax

### ISSUE THREAD

**Issue by smfr** [LeaVerou/css3test#232]
`css-shapes-1.js` has the following tests which I think are incorrect:

`'circle(at right 5% top)',`
`'circle(at right 5% top) margin-box',`

because they use the 3-value position syntax which is not allowed in `<position>` according to https://www.w3.org/TR/css-values-3/#position

**Comment by LeaVerou** [comment]
Ah yes:

> Note: The [background-position](https://www.w3.org/TR/css3-background/#propdef-background-position) property also accepts a three-value syntax. This has been disallowed generically because it creates parsing ambiguities when combined with other length or percentage components in a property value.
