### ISSUE TITLE
css-values-4 trig tests are broken

### ISSUE THREAD

**Issue by smfr** [LeaVerou/css3test#233]
The tests for `sin()`, `cos()` etc are trying to apply `sin(45deg)` as a value for the `width` property, which doesn't work because it has no units.

**Comment by LeaVerou** [comment]
Yup, this should be fixed. I guess `calc(sin(45deg) * 100px)` would work?

**Comment by smfr** [comment]
Yes, that should be fine.

**Comment by Zefling** [comment]
I corrected all the tests and tested with Epiphany Browser.
