### ISSUE TITLE
Add dark mode

### ISSUE THREAD

**Issue by SebastianZ** [LeaVerou/css3test#234]
The page is currently pretty bright in colors. There are many different reasons why many people prefer bright colors on dark background.

So I think it would be good to provide an optional dark mode.

For example, this is what I got with just a few little tweaks:

![Page in dark mode](https://user-images.githubusercontent.com/958943/196005635-b8251470-bf63-4af1-8238-b3079753f5fb.png)

Regarding the technical implementation, this should probably be based on a `prefers-color-scheme: dark` media query. In addition to that, there might be an option to switch between the two different color schemes.

Sebastian

**Comment by LeaVerou** [comment]
LGTM!
