### ISSUE TITLE
Chrome <= 23 should fail a flexbox test

### ISSUE THREAD

**Issue by mlms13** [LeaVerou/css3test#37]
With the `flex` shorthand property set to `flex: auto`, the result [should be the same](http://www.w3.org/TR/css3-flexbox/#flex-common) as `flex: 1 1 auto`. In the current stable version of Chrome (23), `flex: auto` doesn't seem to do anything, [as you can see here](http://codepen.io/mlms13/pen/DIKnv). It would be nice if css3test would include a test demonstrating this failure.

**Comment by LeaVerou** [comment]
Please note, in the top left corner:

![image](https://cloud.githubusercontent.com/assets/175836/13071575/69fb6580-d462-11e5-9d22-48ba9602a65a.png)

Sometimes browsers lie about what they support. css3test cannot do anything about that, short of adding them to the “cheaters" list on the sidebar (which most people don't read).

**Comment by dstorey** [comment]
HTML5Test uses a blacklist (because certain mobile browsers were enabling webkit flags without having features supported to boost score, I believe). We could perhaps do that, but it'd be work to maintain.

**Comment by SebastianZ** [comment]
This specific issue regarding `flex` is pretty outdated now. So I close this issue now.

If there is still need to flag such "fake implementations", please open a new issue providing current examples.

Sebastian
