### ISSUE TITLE
`display:-moz-[inline-]grid;` triggers XUL Grid Layout in Firefox

### ISSUE THREAD

**Issue by fbender** [LeaVerou/css3test#55]
Commit d908abaf1c added the CSS Grid Module. The test for `display: grid` and `display: inline-grid` succedes for Firefox, however it does not trigger CSS3 Grid Layout but XUL Grid layout (via `display: -moz-grid;` etc., see https://bugzilla.mozilla.org/show_bug.cgi?id=616605#c10). 

See https://bugzilla.mozilla.org/show_bug.cgi?id=914360 – if that bug does not get fixed, I'd add another disclaimer to the page. Thanks!

**Comment by ExE-Boss** [comment]
[Bug 914360](https://bugzil.la/914360) has now been resolved as part of [bug 1288572](https://bugzil.la/1288572) in Firefox 62.

## See also:
- https://developer.mozilla.org/docs/Web/CSS/display#XUL_values
- https://www.fxsitecompat.com/en-CA/docs/2018/most-of-non-standard-css-display-values-have-been-dropped/
