### ISSUE TITLE
Support CSS basic box model testing

### ISSUE THREAD

**Issue by yisibl** [LeaVerou/css3test#58]
http://dev.w3.org/csswg/css-box/

For example added:

```css
margin: fill;

width: [border-box | content-box]? | available | min-content | max-content | fit-content;

alignment: top | right | bottom | left | center;

child-align: top | middle | bottom | left | right | auto;
```

**Comment by dstorey** [comment]
Basic Box Model is more or less abandoned or is at least going through major refactoring, with features appearing in other modules, as I personally would close this as won't fix. @LeaVerou, thoughts?

“This draft is undergoing changes and many parts are not consistent with other modules of CSS.
Please, refer to CSS level 2 [CSS21] instead for the definition of the basic box model.”

**Comment by LeaVerou** [comment]
Yup, css-box is definitely not ready atm.
