### ISSUE TITLE
Support CSS Logical Properties Level 1

### ISSUE THREAD

**Issue by SebastianZ** [LeaVerou/css3test#88]
Firefox already has support (hidden behind the `layout.css.vertical-text.enabled` preference) for the properties defined in the 'Logical Page Classifications' in the [CSS Logical Properties specification](http://dev.w3.org/csswg/css-logical-props/).

So should the tests for these properties already be added? What about the properties that are currently not supported?

I can create a pull request for this.

Sebastian

**Comment by LeaVerou** [comment]
Sure, a PR would be welcome :)

**Comment by SebastianZ** [comment]
Note that you didn't answer my questions. In the current PR there are just the properties supported by Gecko. Should I also add tests for the other properties?

Sebastian

**Comment by LeaVerou** [comment]
Sorry, yes, feel free to add tests for the other properties too. Thanks!

**Comment by SebastianZ** [comment]
Looks like all my PRs already got merged. So I close this issue now.

Sebastian
